import secdiv from "../assets/secdiv.png";
export const data = [
  {
    id: 0,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 1,
    number: 14,
    title: "TYPES",
    bgColor: "#c03842",
  },
  {
    id: 2,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 3,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 4,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 5,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 6,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 7,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 8,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 9,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
];
