import secdiv from "../assets/secdiv.png";
export const data = [
  {
    id: 0,
    number: 19,
    title: "SPECIAL EFFECTS",
    titleone: "& BGS",
    bgImage: secdiv,
    bgColor: "#c03842",
  },
  {
    id: 1,
    number: 14,
    title: "TYPES",
    bgColor: "#c03842",
  },
  {
    id: 2,
    number: 84,
    title: "CLOTHING",
    // titleone: "& BGS", 
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 3,
    number: 64,
    title: "BACK",
    titleone: "ACCESSORIES",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 4,
    number: 108,
    title: "HAIR",
    // titleone: "& BGS",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 5,
    number: 27,
    title: "EYES",
    // titleone: "& BGS",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 6,
    number: 11,
    title: "FACE",
    titleone: "ACCESSORIES",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 7,
    number: 40,
    title: "HEAD",
    titleone: "ACCESSORIES",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 8,
    number: 26,
    title: "MOUTH",
    // titleone: "& BGS",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
  {
    id: 9,
    number: 29,
    title: "EARRINGS",
    // titleone: "& BGS",
    // bgImage: secdiv,
    // bgColor: "#c03842",
  },
];
